name: Build Android

on:
  [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        arch: [ "arm32", "aarch64", "x86_64", "i686" ]
      fail-fast: false

    name: "Build for ${{matrix.arch}}"

    runs-on: ubuntu-latest

    steps:
      - name: Disable symlinks in git config
        run: git config --global core.symlinks false
        
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt update
          sudo apt install build-essential -y
          export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
          cmake . -B build
          cd build
          make
          
      - name: Upload libraries
        uses: actions/upload-artifact@v2
        with:
          name: libzink_${{matrix.arch}}
          path: /*
